import pandas as pd

keyword_map = {
    'APPAREL': 'Apparel & Clothing', 'UNDERPANTS': 'Apparel & Clothing', 'SWEATER': 'Apparel & Clothing',
    'SWEATSHIRT': 'Apparel & Clothing', 'HAT': 'Apparel & Clothing', 'PANTS': 'Apparel & Clothing',
    'SKIRT': 'Apparel & Clothing', 'SHIRT': 'Apparel & Clothing', 'DRESS': 'Apparel & Clothing',
    'TIGHTS': 'Apparel & Clothing', 'COAT': 'Apparel & Clothing', 'HANDBAG': 'Apparel & Clothing',
    'SOCKS': 'Apparel & Clothing', 'SHOES': 'Apparel & Clothing', 'CLOTHES': 'Apparel & Clothing',
    'APRON': 'Apparel & Clothing', 'SUNGLASSES': 'Apparel & Clothing', 'BAG': 'Apparel & Clothing',
    'JEWELRY': 'Apparel & Clothing', 'BRA': 'Apparel & Clothing', 'UMBRELLA': 'Apparel & Clothing',
    'SWEATBAND': 'Apparel & Clothing', 'SHORTS': 'Apparel & Clothing',
    'UNDERWEAR': 'Apparel & Clothing', 'BOOT': 'Apparel & Clothing', 'SLEEPWEAR': 'Apparel & Clothing',
    'NECKLACE': 'Apparel & Clothing', 'COSTUME_HEADWEAR': 'Apparel & Clothing',
    'PROTECTIVE_GLOVE': 'Apparel & Clothing',
    'WALLET': 'Apparel & Clothing', 'BACKPACK': 'Apparel & Clothing', 'SHOE_INSERT': 'Apparel & Clothing',
    'PAJAMAS': 'Apparel & Clothing', 'RING': 'Apparel & Clothing', 'EARRING': 'Apparel & Clothing',
    'DOLL_CLOTHING': 'Apparel & Clothing', 'SWIMWEAR': 'Apparel & Clothing', 'LEOTARD': 'Apparel & Clothing',
    'SANDAL': 'Apparel & Clothing', 'COORDINATED_OUTFIT': 'Apparel & Clothing', 'WIG': 'Apparel & Clothing',
    'WATCH_BAND': 'Apparel & Clothing', 'ACCESSORY': 'Apparel & Clothing', 'COSTUME_OUTFIT': 'Apparel & Clothing',
    'ROBE': 'Apparel & Clothing', 'COSTUME_MASK': 'Apparel & Clothing', 'SHOELACE': 'Apparel & Clothing',
    'WATCH': 'Apparel & Clothing', 'COIN_PURSE_POUCH': 'Apparel & Clothing', 'EYEGLASS_CASE': 'Apparel & Clothing',
    'BLAZER': 'Apparel & Clothing', 'WAIST_PACK': 'Apparel & Clothing', 'ONE_PIECE_OUTFIT': 'Apparel & Clothing',
    'SUITCASE': 'Apparel & Clothing', 'WAIST_CINCHER': 'Apparel & Clothing', 'OVERALLS': 'Apparel & Clothing',
    'SUIT': 'Apparel & Clothing', 'CHARM': 'Apparel & Clothing', 'SHOE_TREE': 'Apparel & Clothing',
    'FOOTWEAR_CARE_KIT': 'Apparel & Clothing',
    'NECKTIE': 'Apparel & Clothing',
    'HIP_FLASK': 'Apparel & Clothing', 'EYEGLASS_FRAME': 'Apparel & Clothing',
    'LOOSE_CUT_GEM': 'Apparel & Clothing', 'PLECTRUM': 'Apparel & Clothing', 'SCARF': 'Apparel & Clothing',
    'CORSET': 'Apparel & Clothing', 'ADULT_COSTUME': 'Apparel & Clothing', 'SNOW_PANT': 'Apparel & Clothing',
    'OUTERWEAR': 'Apparel & Clothing', 'GARMENT_PROTECTOR_COVER': 'Apparel & Clothing',
    'SWIM_CAP': 'Apparel & Clothing',
    'SHOWER_CAP': 'Apparel & Clothing', 'LEG_SLEEVE': 'Apparel & Clothing', 'ARM_SLEEVE': 'Apparel & Clothing',
    'VEST': 'Apparel & Clothing', 'FASHIONOTHER': 'Apparel & Clothing',
    'MANNEQUIN_CLOTHING_FORM': 'Apparel & Clothing',
    'COSTUME_EYEWEAR': 'Apparel & Clothing', 'SWIM_FIN': 'Apparel & Clothing',
    'CHILDRENS_COSTUME': 'Apparel & Clothing',
    'UNDERGARMENT_THIGH_SLIMMER': 'Apparel & Clothing', 'SHOE_POLISH': 'Apparel & Clothing',
    'TECHNICAL_SPORT_SHOE': 'Apparel & Clothing',
    'BODYSTOCKING': 'Apparel & Clothing', 'KIMONO': 'Apparel & Clothing', 'ETHNIC_WEAR': 'Apparel & Clothing',
    'KURTA': 'Apparel & Clothing', 'SAREE': 'Apparel & Clothing', 'CHOLI': 'Apparel & Clothing',
    'FOOTWEAR': 'Apparel & Clothing', 'BELTS': 'Apparel & Clothing', 'GLOVES': 'Apparel & Clothing',
    'EYEWEAR': 'Apparel & Clothing',
    'SASH': 'Apparel & Clothing', 'BLOUSE': 'Apparel & Clothing', 'DUPATTA': 'Apparel & Clothing',
    'HOSIERY': 'Apparel & Clothing',
    'CLOTH_WRAP': 'Apparel & Clothing', 'COSTUME': 'Apparel & Clothing', 'BABY_COSTUME': 'Apparel & Clothing',
    'FINEOTHER': 'Apparel & Clothing', 'EARMUFF': 'Apparel & Clothing', 'Apparel': 'Apparel & Clothing',
    'SPORT_ACTIVITY_GLOVE': 'Apparel & Clothing',

    'ELECTRONIC': 'Electronics & Tech', 'POWER': 'Electronics & Tech', 'COMPUTER': 'Electronics & Tech',
    'HEADPHONES': 'Electronics & Tech', 'PHONE': 'Electronics & Tech', 'TABLET': 'Electronics & Tech',
    'SIM': 'Electronics & Tech', 'VIDEO': 'Electronics & Tech', 'SCREEN': 'Electronics & Tech',
    'FLASH': 'Electronics & Tech', 'INPUT': 'Electronics & Tech', 'WIRELESS': 'Electronics & Tech',
    'CHARGING': 'Electronics & Tech', 'LIGHT': 'Electronics & Tech', 'DEVICE': 'Electronics & Tech',
    'MEMORY_CARD_READER': 'Electronics & Tech', 'BATTERY': 'Electronics & Tech',
    'VIRTUAL_REALITY_HEADSET': 'Electronics & Tech',
    'SECURITY_CAMERA': 'Electronics & Tech', 'BINOCULAR': 'Electronics & Tech',
    'AUTO_KEY_SHELL': 'Electronics & Tech',
    'GAS_SMOKE_FIRE_ALARM': 'Electronics & Tech', 'NETWORKING_ROUTER': 'Electronics & Tech',
    'MODEM': 'Electronics & Tech',
    'CONTROLLER': 'Electronics & Tech', 'INTEGRATED_STEREO_SYSTEM': 'Electronics & Tech',
    'HEARING_AMPLIFIER': 'Electronics & Tech',
    'SPEAKERS': 'Electronics & Tech', 'MOUSE_PAD': 'Electronics & Tech',
    'NETWORK_INTERFACE_CONTROLLER_ADAPTER': 'Electronics & Tech',
    'KEYBOARDS': 'Electronics & Tech', 'INTERNAL_MEMORY': 'Electronics & Tech',
    'AMAZON_BOOK_READER': 'Electronics & Tech',
    'AMAZON_BOOK_READER_ACCESSORY': 'Electronics & Tech', 'MONITOR': 'Electronics & Tech',
    'CAMCORDER': 'Electronics & Tech',
    'KEYBOARD_MOUSE_SET': 'Electronics & Tech', 'SOUND_CARD': 'Electronics & Tech',
    'CABLE_OR_ADAPTER': 'Electronics & Tech',
    'ANTENNA': 'Electronics & Tech', 'REMOTE_CONTROL': 'Electronics & Tech', 'ELECTRIC_FAN': 'Electronics & Tech',
    'AUDIO_MIXING_CONSOLE': 'Electronics & Tech',
    'SOUND_AND_RECORDING_EQUIPMENT': 'Electronics & Tech',
    'TWO_WAY_RADIO': 'Electronics & Tech', 'OPTICAL_DISC_DRIVE': 'Electronics & Tech',
    'SCANNER': 'Electronics & Tech', 'AV_SIGNAL_SWITCH': 'Electronics & Tech',
    'BLANK_MEDIA': 'Electronics & Tech', 'MULTIPORT_HUB': 'Electronics & Tech', 'CAMERA_FILM': 'Electronics & Tech',
    'CAMERA_TRIPOD': 'Electronics & Tech', 'SYSTEM_CABINET': 'Electronics & Tech',
    'SURVEILANCE_SYSTEMS': 'Electronics & Tech',
    'CAMERA_DIGITAL': 'Electronics & Tech', 'CAMERA_OTHER_ACCESSORIES': 'Electronics & Tech',
    'RADIO': 'Electronics & Tech',
    'GPS_OR_NAVIGATION_SYSTEM': 'Electronics & Tech', 'TELEVISION': 'Electronics & Tech',
    'MP3_PLAYER': 'Electronics & Tech',
    'WEBCAM': 'Electronics & Tech', 'RELAY': 'Electronics & Tech', 'TV_TUNER_CARD': 'Electronics & Tech',
    'BAR_CODE_READER': 'Electronics & Tech', 'HARD_DRIVE_ENCLOSURE': 'Electronics & Tech',
    'UNMANNED_AERIAL_VEHICLE': 'Electronics & Tech',
    'CAPACITOR': 'Electronics & Tech', 'TRANSFORMER': 'Electronics & Tech', 'INTERCONNECT': 'Electronics & Tech',
    'GAMING_EQUIPMENT_ENCLOSURE': 'Electronics & Tech', 'CAMERA_LENSES': 'Electronics & Tech',
    'MICROSCOPES': 'Electronics & Tech',
    'ELECTRIC_LANTERN': 'Electronics & Tech', 'AV_RECEIVER': 'Electronics & Tech',
    'ELECTRIC_MOTOR': 'Electronics & Tech',
    'NETWORK_SWITCH': 'Electronics & Tech', 'CAMERA': 'Electronics & Tech', 'KEYCAP': 'Electronics & Tech',
    'AUDIO_MIDI_INTERFACE': 'Electronics & Tech', 'PHOTOGRAPHIC_FILM': 'Electronics & Tech',
    'SECURITY_SYSTEM': 'Electronics & Tech',
    'RADAR_DETECTOR': 'Electronics & Tech', 'SURVEILLANCE_RECORDER_SYSTEM': 'Electronics & Tech',
    'MEMORY_READER': 'Electronics & Tech',
    'TRANSISTOR': 'Electronics & Tech', 'ALARM': 'Electronics & Tech', 'WEATHER_STATION': 'Electronics & Tech',
    'SATELLITE_RECEIVER': 'Electronics & Tech', 'PA_SYSTEM': 'Electronics & Tech',
    'AUDIO_CD_PLAYER': 'Electronics & Tech',
    'RAM_MEMORY': 'Electronics & Tech', 'RECEIVER_OR_AMPLIFIER': 'Electronics & Tech',
    'DOWNLOADABLE_TV_SERIES': 'Electronics & Tech',
    'DVD_PLAYER_OR_RECORDER': 'Electronics & Tech', 'DOWNLOADABLE_SOFTWARE': 'Electronics & Tech',
    'TUNER': 'Electronics & Tech',
    'CABLE_ASSEMBLY': 'Electronics & Tech', 'FIXED_RESISTOR': 'Electronics & Tech',
    'LOCATION_TRACKER': 'Electronics & Tech',
    'KARAOKE_MACHINE': 'Electronics & Tech', 'RESISTOR': 'Electronics & Tech', 'CABLE': 'Electronics & Tech',
    'SATELLITE_OR_DSS': 'Electronics & Tech', '3D_GLASSES': 'Electronics & Tech',
    'THERMISTOR': 'Electronics & Tech',
    'COMMUNICATIONS_INTEGRATED_CIRCUIT': 'Electronics & Tech', 'VCR': 'Electronics & Tech',
    'DVD': 'Electronics & Tech',
    'BLU-RAY': 'Electronics & Tech', 'VIDEO GAME': 'Electronics & Tech',
    'WIRELESS PHONE ACCESSORY': 'Electronics & Tech',
    'PERSONAL COMPUTERS': 'Electronics & Tech', 'ACCELERATION_SENSOR': 'Electronics & Tech',
    'DIP_SWITCH': 'Electronics & Tech', 'SOFTWARE': 'Electronics & Tech', 'MOBILE_APPLICATION': 'Electronics & Tech',
    'Electronics': 'Electronics & Tech', 'Personal Computers': 'Electronics & Tech',
    'Wireless Phone Accessory': 'Electronics & Tech',
    'Video Game': 'Electronics & Tech', 'Blu-ray': 'Electronics & Tech', 'ROUTER_BIT': 'Electronics & Tech',

    'PET': 'Pet Supplies', 'ANIMAL_COLLAR': 'Pet Supplies', 'ANIMAL_HARNESS': 'Pet Supplies',
    'ANIMAL_CAGE': 'Pet Supplies',
    'LEASH': 'Pet Supplies', 'LITTER_BOX': 'Pet Supplies', 'ANIMAL_LITTER': 'Pet Supplies',
    'ANIMAL_CARRIER': 'Pet Supplies', 'PAW_HOOF_PROTECTOR': 'Pet Supplies', 'ANIMAL_STAIR': 'Pet Supplies',
    'ANIMAL_PERCH': 'Pet Supplies', 'ANIMAL_SHELTER': 'Pet Supplies', 'ANIMAL_RECOVERY_COLLAR_CONE': 'Pet Supplies',
    'VIVARIUM': 'Pet Supplies', 'WILDLIFE_FEEDER': 'Pet Supplies', 'ANIMAL_MUZZLE': 'Pet Supplies',
    'BIRDBATH': 'Pet Supplies', 'HORSE_TACK_EQUIPMENT': 'Pet Supplies',

    'ABIS': 'ABIS', 'MISC_OTHER': 'ABIS', 'Misc.': 'ABIS',

    'TOILET': 'Toiletries & Beauty', 'TOOTH': 'Toiletries & Beauty', 'SHAVING': 'Toiletries & Beauty',
    'MOUTHWASH': 'Toiletries & Beauty',
    'DEODORANT': 'Toiletries & Beauty', 'SHAMPOO': 'Toiletries & Beauty', 'CONDITIONER': 'Toiletries & Beauty',
    'HAIR': 'Toiletries & Beauty',
    'RAZOR_BLADE_CARTRIDGE': 'Toiletries & Beauty', 'ELECTRIC_SHAVER': 'Toiletries & Beauty',
    'CONTACT_LENS_CLEANER': 'Toiletries & Beauty',
    'PERSONAL_CARE_APPLIANCE': 'Toiletries & Beauty', 'MENSTRUAL_CUP': 'Toiletries & Beauty',
    'DENTAL_FLOSS': 'Toiletries & Beauty',
    'SELF_TANNER': 'Toiletries & Beauty', 'ORAL_IRRIGATOR': 'Toiletries & Beauty', 'TAMPON': 'Toiletries & Beauty',
    'HAND_SANITIZER': 'Toiletries & Beauty', 'EPILATOR': 'Toiletries & Beauty', 'FALSE_EYELASH': 'Toiletries & Beauty',
    'SKIN': 'Toiletries & Beauty', 'BEAUTY': 'Toiletries & Beauty', 'FACIAL': 'Toiletries & Beauty',
    'COSMETIC': 'Toiletries & Beauty', 'LIP': 'Toiletries & Beauty', 'EYEBROW': 'Toiletries & Beauty',
    'NAIL': 'Toiletries & Beauty', 'EYELID': 'Toiletries & Beauty', 'MAKE_UP': 'Toiletries & Beauty',
    'BODY_LUBRICANT': 'Toiletries & Beauty', 'ASTRINGENT_SUBSTANCE': 'Toiletries & Beauty',
    'FACE_SHAPING_MAKEUP': 'Toiletries & Beauty', 'MAKEUP_PRIMER': 'Toiletries & Beauty',
    'BATHING_SPONGE': 'Toiletries & Beauty', 'PERSONAL_FRAGRANCE': 'Toiletries & Beauty',
    'COTTON_PAD': 'Toiletries & Beauty', 'MOISTURIZING_SOCK_GLOVE': 'Toiletries & Beauty',
    'MASCARA': 'Toiletries & Beauty', 'EYELASH_CURLER': 'Toiletries & Beauty', 'SLEEP_MASK': 'Toiletries & Beauty',
    'Health and Beauty': 'Toiletries & Beauty', 'CUTICLE_PUSHER': 'Toiletries & Beauty',
    'FRAGRANCE': 'Toiletries & Beauty',
    'TOPICALS': 'Toiletries & Beauty', 'CONTACT_LENSES': 'Toiletries & Beauty',

    'DISH': 'Kitchen & Dining', 'NAPKIN': 'Kitchen & Dining', 'PAPER_TOWEL': 'Kitchen & Dining',
    'FORK': 'Kitchen & Dining',
    'TRASH': 'Kitchen & Dining', 'ROLLING_PIN': 'Kitchen & Dining', 'COFFEE_MAKER': 'Kitchen & Dining',
    'ICE': 'Kitchen & Dining',
    'PITCHER': 'Kitchen & Dining', 'CUTTING': 'Kitchen & Dining', 'FUNNEL': 'Kitchen & Dining',
    'SAUTE_FRY_PAN': 'Kitchen & Dining',
    'MEASURING_CUP': 'Kitchen & Dining', 'COFFEE': 'Kitchen & Dining', 'KITCHEN': 'Kitchen & Dining',
    'KITCHEN_TOOLS': 'Kitchen & Dining',
    'COOKWARE_SET': 'Kitchen & Dining', 'SERVEWARE': 'Kitchen & Dining',
    'COUNTERTOP_GRIDDLE_APPLIANCE': 'Kitchen & Dining',
    'THERMOS': 'Kitchen & Dining', 'COOKTOP': 'Kitchen & Dining', 'SPOON': 'Kitchen & Dining',
    'MEAL_HOLDER': 'Kitchen & Dining',
    'BOTTLE': 'Kitchen & Dining', 'ROASTING_PAN': 'Kitchen & Dining', 'SLOW_COOKER': 'Kitchen & Dining',
    'SHEET_PAN': 'Kitchen & Dining',
    'TOASTER': 'Kitchen & Dining', 'CHOPSTICK': 'Kitchen & Dining', 'ELECTRIC_WATER_BOILER': 'Kitchen & Dining',
    'DUTCH_OVENS': 'Kitchen & Dining',
    'KNIFE': 'Kitchen & Dining', 'AIR_FRYER': 'Kitchen & Dining', 'TRIVET': 'Kitchen & Dining',
    'PRESSURE_COOKER': 'Kitchen & Dining',
    'SKEWER': 'Kitchen & Dining', 'COCKTAIL_SHAKER': 'Kitchen & Dining', 'GARLIC_PRESS': 'Kitchen & Dining',
    'TONG_UTENSIL': 'Kitchen & Dining',
    'BAKEWARE_SET': 'Kitchen & Dining', 'BAR_TOOL_SET': 'Kitchen & Dining', 'REFRIGERATOR': 'Kitchen & Dining',
    'TRAY': 'Kitchen & Dining',
    'CASSEROLES': 'Kitchen & Dining', 'MICROWAVE_OVEN': 'Kitchen & Dining', 'POT_HOLDER': 'Kitchen & Dining',
    'PLACEMAT': 'Kitchen & Dining',
    'COUNTERTOP_OVEN': 'Kitchen & Dining', 'COUNTERTOP_BURNER': 'Kitchen & Dining', 'PIPING_TIP': 'Kitchen & Dining',
    'MILK_FROTHER': 'Kitchen & Dining', 'SOUS_VIDE_MACHINE': 'Kitchen & Dining', 'COOKWARE': 'Kitchen & Dining',
    'STOVETOP_KETTLE': 'Kitchen & Dining', 'FLATWARE': 'Kitchen & Dining', 'CORE_PIT_REMOVER': 'Kitchen & Dining',
    'DEEP_FRYER': 'Kitchen & Dining', 'COOKING_POT': 'Kitchen & Dining', 'MORTAR_AND_PESTLE_SET': 'Kitchen & Dining',
    'BARBECUE_TOOL_SET': 'Kitchen & Dining', 'SODA_MAKER': 'Kitchen & Dining', 'WHISK_UTENSIL': 'Kitchen & Dining',
    'RANGE': 'Kitchen & Dining', 'VACUUM_SEALER_MACHINE': 'Kitchen & Dining', 'GRIDDLE_PLATE': 'Kitchen & Dining',
    'PASTA_MAKER': 'Kitchen & Dining', 'REFRIGERATION_APPLIANCE': 'Kitchen & Dining', 'CUTLERY': 'Kitchen & Dining',
    'COOLING_RACK': 'Kitchen & Dining', 'BAKEWARE': 'Kitchen & Dining', 'DINNERWARE': 'Kitchen & Dining',
    'FREEZER': 'Kitchen & Dining',
    'VENT_HOOD': 'Kitchen & Dining', 'HOOKAH': 'Kitchen & Dining',
    'COOKING_OVEN': 'Kitchen & Dining', 'LAB_UTENSIL': 'Kitchen & Dining', 'COCKTAIL_MIX': 'Kitchen & Dining',
    'DOUBLE_BOILERS': 'Kitchen & Dining', 'Kitchen': 'Kitchen & Dining',

    'TAPE': 'Tools & Hardware', 'PLUMBING': 'Tools & Hardware', 'SCREWDRIVER': 'Tools & Hardware',
    'WINDOW': 'Tools & Hardware',
    'HARDWARE': 'Tools & Hardware', 'ADHESIVE': 'Tools & Hardware', 'SHARP': 'Tools & Hardware',
    'SHOVEL': 'Tools & Hardware',
    'LOCK': 'Tools & Hardware', 'FILTER': 'Tools & Hardware', 'UTILITY': 'Tools & Hardware',
    'MATERIAL': 'Tools & Hardware',
    'SANDER': 'Tools & Hardware', 'LADDER': 'Tools & Hardware', 'RECIPROCATING_HEDGE_TRIMMER': 'Tools & Hardware',
    'PAINT': 'Tools & Hardware', 'LINT_REMOVER': 'Tools & Hardware', '3D_PRINTER': 'Tools & Hardware',
    'MECHANICAL_COMPONENTS': 'Tools & Hardware', 'MECHANICAL_FASTENERS': 'Tools & Hardware',
    'SAW_BLADE': 'Tools & Hardware',
    'MULTITOOL': 'Tools & Hardware', 'GARDEN_SHEAR_SCISSORS': 'Tools & Hardware',
    'HOOK_LOOP_FASTENER': 'Tools & Hardware', 'FASTENER_DRIVE_BIT': 'Tools & Hardware', 'TWEEZER': 'Tools & Hardware',
    'CIRCUIT_BREAKER': 'Tools & Hardware', 'LAB_SUPPLY': 'Tools & Hardware', 'CABLE_TIE': 'Tools & Hardware',
    'CANNED_AIR': 'Tools & Hardware', 'BUNGEE_CORD': 'Tools & Hardware', 'SEALANT': 'Tools & Hardware',
    'ZIPPER_FASTENER': 'Tools & Hardware',
    'AIR_COMPRESSOR': 'Tools & Hardware', 'HOSE_PIPE_FITTING': 'Tools & Hardware', 'DRILL_BITS': 'Tools & Hardware',
    'INDUSTRIAL_CASTERS': 'Tools & Hardware', 'WATER_PURIFICATION_UNIT': 'Tools & Hardware',
    'ROTARY_TOOL': 'Tools & Hardware',
    'MACHINE_LUBRICANT': 'Tools & Hardware', 'AUTO_OIL': 'Tools & Hardware', 'VALVE': 'Tools & Hardware',
    'AIR_GUN': 'Tools & Hardware',
    'BUCKET': 'Tools & Hardware', 'TONNEAU_COVER': 'Tools & Hardware', 'STEP_S TOOL': 'Tools & Hardware',
    'ELECTRICITY_GENERATOR': 'Tools & Hardware',
    'TOOL_BELT': 'Tools & Hardware', 'MUFFLER': 'Tools & Hardware', 'MECHANICAL_BELT': 'Tools & Hardware',
    'RULER': 'Tools & Hardware',
    'CORD_MANAGEMENT_COVER': 'Tools & Hardware', 'MAPS': 'Tools & Hardware', 'DYE': 'Tools & Hardware',
    'TOOLS': 'Tools & Hardware',
    'WIRE_STRIPPER': 'Tools & Hardware', 'CHAINSAW': 'Tools & Hardware', 'BLOWTORCH': 'Tools & Hardware',
    'SAW': 'Tools & Hardware',
    'DRILL': 'Tools & Hardware', 'WRENCH': 'Tools & Hardware', 'PLUG_STOPPER': 'Tools & Hardware',
    'SHIPPING_BOX': 'Tools & Hardware',
    'WASHER': 'Tools & Hardware', 'GASKETS': 'Tools & Hardware', 'FUSE': 'Tools & Hardware',
    'LAB_CHEMICAL': 'Tools & Hardware',
    'SURFACE_PROTECTION_WAX': 'Tools & Hardware', 'LINEAR_GUIDES_AND_RAILS': 'Tools & Hardware',
    'ELECTRICAL_PLUG': 'Tools & Hardware',
    'HAMMER_MALLET': 'Tools & Hardware', 'WHEEL_CUTTER': 'Tools & Hardware',
    'SCREWS': 'Tools & Hardware', 'WIRE': 'Tools & Hardware', 'INSULATION': 'Tools & Hardware',
    'RANGEFINDER': 'Tools & Hardware',
    'METAL_DETECTOR': 'Tools & Hardware', 'WEAPON_CASE': 'Tools & Hardware', 'WINDING_REEL': 'Tools & Hardware',
    'LEVEL': 'Tools & Hardware',
    'DISC_GRINDER_TOOL': 'Tools & Hardware', 'PLIERS': 'Tools & Hardware', 'TOOL_CHUCK': 'Tools & Hardware',
    'SCREW_GUN': 'Tools & Hardware',
    'WEED_MOSS_CONTROL_AGENT': 'Tools & Hardware', 'PUMP_SPRAYER': 'Tools & Hardware', 'BOLTS': 'Tools & Hardware',
    'CAULKS': 'Tools & Hardware',
    'SNAP_FASTENER': 'Tools & Hardware', 'BUCKLE': 'Tools & Hardware', 'ANCHOR_STAKE': 'Tools & Hardware',
    'GUN_SLING': 'Tools & Hardware',
    'SQUEEGEE': 'Tools & Hardware', 'CAMERA_CLEANER': 'Tools & Hardware', 'EYEGLASS_REPAIR_KIT': 'Tools & Hardware',
    'WALL_PLATE': 'Tools & Hardware', 'BLEACH': 'Tools & Hardware', 'ELECTROMECHANICAL_GAUGE': 'Tools & Hardware',
    'ELECTRICAL_DISTRIBUTION_BOARD': 'Tools & Hardware', 'ELECTRICAL_OUTLET': 'Tools & Hardware',
    'BISS': 'Tools & Hardware',
    'HOT_GLUE_GUN': 'Tools & Hardware', 'GROMMETS': 'Tools & Hardware', 'CISTERN': 'Tools & Hardware',
    'ELECTRICAL_HOUSING': 'Tools & Hardware',
    'TOGGLE_SWITCH': 'Tools & Hardware', 'INDUSTRIAL_HOSE': 'Tools & Hardware', 'HOUSEHOLD_VARNISH': 'Tools & Hardware',
    'CHISEL': 'Tools & Hardware',
    'POLISHING_BUFFING_TOOL': 'Tools & Hardware', 'HOT_MELT': 'Tools & Hardware', 'PULLEYS': 'Tools & Hardware',
    'RIVET': 'Tools & Hardware', 'AXE': 'Tools & Hardware', 'THREADING_TAPS': 'Tools & Hardware',
    'JANITORIAL_SUPPLY': 'Tools & Hardware',
    'HEAT_PRESS': 'Tools & Hardware', 'DIE_CUT_MACHINE': 'Tools & Hardware', 'PRESSER_FOOT': 'Tools & Hardware',
    'SEWING_MACHINE': 'Tools & Hardware', 'GREASE_GUN': 'Tools & Hardware', 'END_MILLS': 'Tools & Hardware',
    'ROLLER_CHAIN': 'Tools & Hardware', 'SEALS': 'Tools & Hardware', 'PLASTIC_TUBING': 'Tools & Hardware',
    'METALS': 'Tools & Hardware', 'THREADING_DIES': 'Tools & Hardware', 'SPROCKETS': 'Tools & Hardware',
    'PUNCH_TOOL': 'Tools & Hardware', 'MACHINE_THREADING_TOOL': 'Tools & Hardware', 'SHAFT_COLLAR': 'Tools & Hardware',
    'METAL_TUBING': 'Tools & Hardware', 'FLEXIBLE_COUPLINGS': 'Tools & Hardware',
    'TOOLS & HOME IMPROVEMENT': 'Tools & Hardware',
    'FLASK': 'Tools & Hardware', 'CIGAR_CUTTER': 'Tools & Hardware',
    'DENT_REMOVAL_TOOL': 'Tools & Hardware', 'LAB_PUMP': 'Tools & Hardware', 'ELECTRIC_STIRRER': 'Tools & Hardware',
    'NAVIGATION_COMPASS': 'Tools & Hardware', 'GUN_SUPPORT': 'Tools & Hardware', 'GUN_GRIP': 'Tools & Hardware',
    'ELECTROSHOCK_WEAPON': 'Tools & Hardware', 'GUN_RACK': 'Tools & Hardware',
    'Tools & Home Improvement': 'Tools & Hardware',
    'ZENER_DIODE': 'Tools & Hardware',

    'INK': 'Office, Books & Media', 'FILE': 'Office, Books & Media', 'STORAGE': 'Office, Books & Media',
    'CALENDAR': 'Office, Books & Media',
    'PLANNER': 'Office, Books & Media', 'OFFICE': 'Office, Books & Media', 'ENVELOPE': 'Office, Books & Media',
    'PAPER': 'Office, Books & Media', 'PINBOARD': 'Office, Books & Media', 'DESK': 'Office, Books & Media',
    'NOTE': 'Office, Books & Media',
    'TIMER': 'Office, Books & Media', 'STICKER': 'Office, Books & Media', 'SUPPLIES': 'Office, Books & Media',
    'PEN': 'Office, Books & Media',
    'CARD_STOCK': 'Office, Books & Media', 'WRITING_INSTRUMENT': 'Office, Books & Media',
    'GREETING_CARD': 'Office, Books & Media',
    'IRON_ON_TRANSFER_DESIGN': 'Office, Books & Media', 'SIGNAGE': 'Office, Books & Media',
    'WRITING_BOARD': 'Office, Books & Media',
    'ERASER': 'Office, Books & Media', 'RUBBER_STAMP': 'Office, Books & Media', 'BADGE_HOLDER': 'Office, Books & Media',
    'DECORATIVE_MAGNET': 'Office, Books & Media',
    'GIFT_CARD': 'Office, Books & Media', 'KEYCHAIN': 'Office, Books & Media', 'LABEL': 'Office, Books & Media',
    'LASER_PRINTER_TONER': 'Office, Books & Media',
    'BOOKMARK': 'Office, Books & Media', 'LAMINATOR': 'Office, Books & Media',
    'CARD_DOCUMENT_SLEEVE': 'Office, Books & Media', 'BINDER_DIVIDER': 'Office, Books & Media',
    'STORE_FIXTURES_AND_EQUIPMENT': 'Office, Books & Media', 'THREAD_CORD': 'Office, Books & Media',
    'DECORATIVE_RIBBON_TRIM': 'Office, Books & Media',
    'GLITTER': 'Office, Books & Media', 'TEMPORARY_TATTOO': 'Office, Books & Media',
    'TEMPLATE_STENCIL': 'Office, Books & Media',
    'BOOKS_1973_AND_LATER': 'Office, Books & Media', 'MAGAZINES': 'Office, Books & Media',
    'GLOBE': 'Office, Books & Media', 'BOOK_COVER': 'Office, Books & Media', 'BOOK': 'Office, Books & Media',
    'PRINTS AND POSTERS': 'Office, Books & Media',
    'Paperback': 'Office, Books & Media', 'STAMPS': 'Office, Books & Media', 'OFFICE PRODUCT': 'Office, Books & Media',
    'MUSIC_POPULAR': 'Office, Books & Media', 'MUSIC_POPULAR_VINYL': 'Office, Books & Media',
    'MUSIC': 'Office, Books & Media',
    'DOWNLOADABLE_AUDIO': 'Office, Books & Media', 'PRINTED_MEDIA': 'Office, Books & Media',
    'HARDCOVER': 'Office, Books & Media',
    'PODCAST_EPISODIC_AUDIO_BROADCAST': 'Office, Books & Media', 'TICKET_ROLL': 'Office, Books & Media',
    'PRINTS_AND_POSTERS': 'Office, Books & Media',
    'PROTOTYPING_BOARD': 'Office, Books & Media', 'Office Product': 'Office, Books & Media',
    'SCISSORS': 'Office, Books & Media',
    'HOLE_PUNCH': 'Office, Books & Media', 'STAPLER': 'Office, Books & Media', 'CRAFT': 'Office, Books & Media',
    'CALCULATOR': 'Office, Books & Media',
    'PRINTER': 'Office, Books & Media',

    'FOOD': 'Food & Beverage', 'DRINK': 'Food & Beverage', 'DRINKING': 'Food & Beverage',
    'JUICE': 'Food & Beverage', 'DAIRY': 'Food & Beverage', 'HERB': 'Food & Beverage',
    'MEAT': 'Food & Beverage', 'JERKY': 'Food & Beverage', 'GROCERY': 'Food & Beverage',
    'POULTRY': 'Food & Beverage', 'SUGAR': 'Food & Beverage', 'CULINARY': 'Food & Beverage',
    'VEGETABLE': 'Food & Beverage', 'SNACK': 'Food & Beverage', 'SAUCE': 'Food & Beverage',
    'POPCORN': 'Food & Beverage', 'SALAD': 'Food & Beverage', 'TEA': 'Food & Beverage',
    'CEREAL': 'Food & Beverage', 'CRACKER': 'Food & Beverage', 'COOKIE': 'Food & Beverage',
    'BAKING': 'Food & Beverage', 'NUTS': 'Food & Beverage', 'FRUIT': 'Food & Beverage',
    'FLOUR': 'Food & Beverage', 'BREAD': 'Food & Beverage', 'SOUP': 'Food & Beverage',
    'HONEY': 'Food & Beverage', 'THICKENING_AGENT': 'Food & Beverage', 'PASTRY': 'Food & Beverage',
    'CONDIMENT': 'Food & Beverage', 'LEGUME': 'Food & Beverage', 'NOODLE': 'Food & Beverage',
    'NUT_BUTTER': 'Food & Beverage', 'MEAL_REPLACEMENT_BEVERAGE': 'Food & Beverage',
    'PRETZEL': 'Food & Beverage', 'PICKLE': 'Food & Beverage', 'CHOCOLATE_CANDY': 'Food & Beverage',
    'CHEWING_GUM': 'Food & Beverage', 'CANDY': 'Food & Beverage', 'ALCOHOLIC_BEVERAGE': 'Food & Beverage',
    'WATER': 'Food & Beverage', 'VINEGAR': 'Food & Beverage', 'LEAVENING_AGENT': 'Food & Beverage',
    'MILK_SUBSTITUTE': 'Food & Beverage', 'NUT_AND_SEED': 'Food & Beverage', 'SYRUP': 'Food & Beverage',
    'CAKE': 'Food & Beverage', 'SEASONING': 'Food & Beverage', 'FISH': 'Food & Beverage',
    'SHELLFISH': 'Food & Beverage', 'PIZZA': 'Food & Beverage', 'BEVERAGE': 'Food & Beverage',
    'BABY_FORMULA': 'Food & Beverage', 'EGG': 'Food & Beverage', 'EDIBLE_OIL_ANIMAL': 'Food & Beverage',
    'SPIRITS': 'Food & Beverage', 'BEER': 'Food & Beverage', 'OLIVE': 'Food & Beverage',
    'WINE': 'Food & Beverage', 'PREPARED_DOUGH': 'Food & Beverage', 'TOFU': 'Food & Beverage',
    'DONUT': 'Food & Beverage', 'FUDGE': 'Food & Beverage', 'TEMPEH': 'Food & Beverage',
    'RELISH': 'Food & Beverage', 'EXTRACT': 'Food & Beverage', 'PIE': 'Food & Beverage',
    'Grocery': 'Food & Beverage', 'BEVERAGE_INSULATOR': 'Food & Beverage',

    'BED': 'Home & Baby', 'BODY_POSITIONER': 'Home & Baby', 'TOWEL': 'Home & Baby', 'BATHWATER': 'Home & Baby',
    'FURNITURE': 'Home & Baby', 'HEATER': 'Home & Baby', 'LAMP': 'Home & Baby', 'STAND': 'Home & Baby',
    'MOP': 'Home & Baby', 'BROOM': 'Home & Baby', 'CLEANING': 'Home & Baby', 'ROD': 'Home & Baby',
    'HOME': 'Home & Baby', 'CANDLE': 'Home & Baby', 'SHOWERHEAD': 'Home & Baby', 'LAUNDRY': 'Home & Baby',
    'AREA': 'Home & Baby', 'INCENSE': 'Home & Baby', 'PURIFIER': 'Home & Baby', 'GARLAND': 'Home & Baby',
    'DISPLAY': 'Home & Baby', 'CADDY': 'Home & Baby', 'PILLOWCASE': 'Home & Baby', 'CURTAIN': 'Home & Baby',
    'CONTAINER': 'Home & Baby', 'TEMPORARY_GATE': 'Home & Baby', 'WALL_ART': 'Home & Baby',
    'DISPOSABLE_INCONTINENCE_SURFACE_PROTECTOR': 'Home & Baby', 'HUMIDIFIER': 'Home & Baby',
    'GIFT_WRAP': 'Home & Baby', 'TREE_TOPPER': 'Home & Baby',
    'BLANKET': 'Home & Baby', 'THERMOMETER': 'Home & Baby', 'SPRAY_BOTTLE': 'Home & Baby',
    'HUMIDITY_METER': 'Home & Baby',
    'FITTED_SHEET': 'Home & Baby', 'TABLE': 'Home & Baby', 'VACUUM_CLEANER': 'Home & Baby',
    'PICTURE_FRAME': 'Home & Baby',
    'RUG': 'Home & Baby', 'FAUCET': 'Home & Baby', 'FIGURINE': 'Home & Baby', 'MAILBOX': 'Home & Baby',
    'DRAFT_STOPPER': 'Home & Baby', 'AUTO_ACCESSORY': 'Home & Baby', 'SCULPTURE': 'Home & Baby',
    'ESSENTIAL_OIL': 'Home & Baby',
    'DECORATIVE_SIGNAGE': 'Home & Baby', 'DECORATIVE_CUTOUT': 'Home & Baby', 'TEXTILE_IRON': 'Home & Baby',
    'TEXTILE_DEODORIZER': 'Home & Baby', 'WIND_CHIME': 'Home & Baby', 'BANNER': 'Home & Baby',
    'BATHTUB_SHOWER_MAT': 'Home & Baby',
    'DUVET_COVER': 'Home & Baby', 'HANDRAIL': 'Home & Baby', 'HANGING_ORNAMENT': 'Home & Baby', 'SHELF': 'Home & Baby',
    'TEMPORARY_HANGER_HOOK': 'Home & Baby', 'FOOTREST': 'Home & Baby', 'BACKDROP': 'Home & Baby',
    'DOORSTOP': 'Home & Baby', 'MATTRESS': 'Home & Baby', 'PLAYHOUSE': 'Home & Baby', 'BASKET': 'Home & Baby',
    'PICTURE_HANGER': 'Home & Baby', 'FABRIC': 'Home & Baby', 'DUST_REMOVAL_TOOL': 'Home & Baby', 'SAFE': 'Home & Baby',
    'ART_EASEL': 'Home & Baby', 'BENCH': 'Home & Baby', 'BOOKEND': 'Home & Baby',
    'OTTOMAN': 'Home & Baby', 'AROBA_DIFFUSER': 'Home & Baby', 'MATTRESS_COVER': 'Home & Baby',
    'AIR_MATTRESS': 'Home & Baby',
    'NOISE_MACHINE': 'Home & Baby', 'SWING': 'Home & Baby', 'HANGING_MOBILE': 'Home & Baby',
    'CHANGING_PAD_COVER': 'Home & Baby',
    'FABRIC_SOFTENER': 'Home & Baby', 'INFANT_TODDLER_CAR_SEAT': 'Home & Baby', 'BASSINET': 'Home & Baby',
    'BABY_CARRIER': 'Home & Baby', 'PACIFIER': 'Home & Baby', 'IRONING_BOARD': 'Home & Baby',
    'DRYING_RACK': 'Home & Baby',
    'FOUNTAIN': 'Home & Baby', 'DOOR': 'Home & Baby', 'HOUSEHOLD_STAIN': 'Home & Baby', 'VASE': 'Home & Baby',
    'WREATH': 'Home & Baby', 'SEWING_TOOL_SET': 'Home & Baby', 'CUP_HOLDER': 'Home & Baby',
    'DRAWER_SLIDE': 'Home & Baby',
    'STOOL_SEATING': 'Home & Baby', 'WEATHER_STRIPPING': 'Home & Baby', 'DRAIN_STRAINER': 'Home & Baby',
    'TILE': 'Home & Baby',
    'CABINET': 'Home & Baby', 'HEADBOARD': 'Home & Baby', 'PANTRY': 'Home & Baby', 'URN': 'Home & Baby',
    'SIPHON': 'Home & Baby',
    'BREAST_PUMP': 'Home & Baby', 'REUSABLE_INCONTINENCE_SURFACE_PROTECTOR': 'Home & Baby', 'SOFA': 'Home & Baby',
    'FIREPLACE': 'Home & Baby', 'FLAT_SHEET': 'Home & Baby', 'BABY_SEAT': 'Home & Baby', 'JAR': 'Home & Baby',
    'ANTI_FATIGUE_FLOOR_MAT': 'Home & Baby', 'FLAME_WICK': 'Home & Baby', 'PLAY_WORKSTATION': 'Home & Baby',
    'GRILL_SMOKER_COVER': 'Home & Baby', 'DECORATIVE_POM_POM': 'Home & Baby', 'PLAY_SLIDE': 'Home & Baby',
    'HAMMOCK': 'Home & Baby', 'BLOWER_INFLATED_DECORATION': 'Home & Baby', 'BATHTUB': 'Home & Baby',
    'BATHTUB_SHOWER_TRIM_KIT': 'Home & Baby', 'CRIB': 'Home & Baby', 'PLAYARD': 'Home & Baby',
    'COLLAPSIBLE_PLAY_STRUCTURE': 'Home & Baby', 'SNOW_GLOBE': 'Home & Baby', 'POTPOURRI_SACHET': 'Home & Baby',
    'STROLLER': 'Home & Baby', 'OUTBUILDING': 'Home & Baby', 'BABY_RATTLE': 'Home & Baby',
    'CHANGING_PAD': 'Home & Baby',
    'MAKEUP_VANITY': 'Home & Baby', 'DRYER': 'Home & Baby', 'AIR_COOLER': 'Home & Baby', 'HOT_TUB': 'Home & Baby',
    'SAUNA': 'Home & Baby', 'TARP': 'Home & Baby', 'CORD_ROPE': 'Home & Baby',
    'SHADE_SAIL': 'Home & Baby', 'HAND_FAN': 'Home & Baby', 'ROOM_DIVIDER': 'Home & Baby',
    'FLOOR_COVER': 'Home & Baby', 'SHOWER_ENCLOSURE': 'Home & Baby', 'HEATING_STOVE': 'Home & Baby',
    'FIRE_GRATE': 'Home & Baby', 'INCUBATOR': 'Home & Baby', 'WIND_SPINNER': 'Home & Baby',
    'VINE': 'Home & Baby', 'FENCE_PANEL': 'Home & Baby', 'FLOWERS': 'Home & Baby', 'GUILD_BABY': 'Home & Baby',
    'LAWN & PATIO': 'Home & Baby', 'STEP_STOOL': 'Home & Baby', 'PLASTICS': 'Home & Baby', 'HUMIDOR': 'Home & Baby',
    'GIFTS_AND_OCCASIONS': 'Home & Baby', 'ARTIFICIAL_TREE': 'Home & Baby', 'LUGGAGE': 'Home & Baby',

    'WRIST': 'Health & Wellness', 'HEALTH': 'Health & Wellness', 'NUTRITIONAL': 'Health & Wellness',
    'HEALTHCARE': 'Health & Wellness',
    'MEDICATION': 'Health & Wellness', 'VITAMIN': 'Health & Wellness', 'SUPPLEMENT': 'Health & Wellness',
    'BRACE': 'Health & Wellness',
    'PILL': 'Health & Wellness', 'EARPLUG': 'Health & Wellness', 'THERAPEUTIC_THERMAL_COMPRESS': 'Health & Wellness',
    'MASSAGER': 'Health & Wellness', 'DUMBBELL': 'Health & Wellness', 'FOOT_SCRAPER': 'Health & Wellness',
    'SAFETY_MASK': 'Health & Wellness', 'SEXUAL_WELLNESS': 'Health & Wellness', 'TEETHER': 'Health & Wellness',
    'MEDICAL_COMPRESSION_GARMENT': 'Health & Wellness', 'BODY_STRAP': 'Health & Wellness',
    'GLUCOSE_METER': 'Health & Wellness',
    'SYRINGE': 'Health & Wellness', 'RESPIRATOR': 'Health & Wellness', 'INCONTINENCE_PROTECTOR': 'Health & Wellness',
    'MEDICAL_TEST_STRIP': 'Health & Wellness', 'HAND_STRENGTHENER': 'Health & Wellness',
    'WEIGH_SCALE': 'Health & Wellness',
    'MUSCLE_ROLLER': 'Health & Wellness', 'WALKER': 'Health & Wellness', 'FIRST_AID_KIT': 'Health & Wellness',
    'NASAL_ASPIRATOR': 'Health & Wellness', 'CORRECTIVE_EYEGLASSES': 'Health & Wellness',
    'ELECTRIC_HEATING_PAD': 'Health & Wellness',
    'CONDOM': 'Health & Wellness', 'M_GUARD': 'Health & Wellness',
    'CLINICAL_DIAGNOSTIC_TESTING_KIT': 'Health & Wellness',
    'CHEMICAL_TEST_STRIP': 'Health & Wellness', 'FACE_SHIELD': 'Health & Wellness', 'BLOOD_LANCET': 'Health & Wellness',
    'SURVIVAL_KIT': 'Health & Wellness', 'MOUTH_GUARD': 'Health & Wellness', 'SELF_DEFENSE_SPRAY': 'Health & Wellness',
    'SHIN_GUARD': 'Health & Wellness', 'WALKING_STICK': 'Health & Wellness', 'ENEMA_DOUCHE': 'Health & Wellness',
    'MEDICAL_SCRUB_SET': 'Health & Wellness', 'MASSAGE_STICK': 'Health & Wellness', 'STETHOSCOPE': 'Health & Wellness',
    'DAILY_LIVING_AIDS': 'Health & Wellness', 'NICOTINE_REPLACEMENT': 'Health & Wellness',
    'PROTECTIVE_GEAR': 'Health & Wellness',
    'STATIONARY_BICYCLE': 'Health & Wellness', 'EXERCISE_MAT': 'Health & Wellness',
    'TREADMILL': 'Health & Wellness', 'JUMP_ROPE': 'Health & Wellness', 'WEIGHT_RACK': 'Health & Wellness',
    'BARBELL': 'Health & Wellness', 'EXERCISE_BAND': 'Health & Wellness',
    'EXERCISE_STRAP': 'Health & Wellness', 'KNEE_PAD': 'Health & Wellness',
    'IMPACT_PROTECTION_GEAR': 'Health & Wellness', 'WEIGHTLIFTING_BELT': 'Health & Wellness',
    'BICYCLE_PEDAL': 'Health & Wellness', 'BALANCE_BOARD': 'Health & Wellness',
    'SELF_BALANCING_ELECTRIC_VEHICLE': 'Health & Wellness', 'STRENGTH_TRAINING_MACHINE': 'Health & Wellness',
    'ABDOMINAL_EXERCISER': 'Health & Wellness', 'WEARABLE_WEIGHT': 'Health & Wellness',
    'EXERCISE_MACHINE': 'Health & Wellness', 'FITNESS_STEPPER': 'Health & Wellness',
    'FITNESS_HOOP': 'Health & Wellness', 'ELASTIC_BAND': 'Health & Wellness',
    'BOXING_GLOVE': 'Health & Wellness', 'PULL_UP_BAR': 'Health & Wellness',
    'EXERCISE_STEP_PLATFORM': 'Health & Wellness', 'HELMET': 'Health & Wellness',
    'ROWING_MACHINE': 'Health & Wellness', 'WEIGHT_PLATE': 'Health & Wellness',
    'KETTLEBELL': 'Health & Wellness', 'CYCLING_EQUIPMENT': 'Health & Wellness',
    'SPORT_FACE_MASK': 'Health & Wellness',
    'HANDLE_GRIP': 'Health & Wellness', 'SHOCK_ABSORBER': 'Health & Wellness',
    'BALL_LAUNCHER': 'Health & Wellness',
    'FITNESS_EQUIPMENT': 'Health & Wellness', 'SPORT_BINDING': 'Health & Wellness',
    'SNOWBOARD_BINDING': 'Health & Wellness',

    'PLANT': 'Outdoors & Recreation', 'INSECT': 'Outdoors & Recreation', 'PLANTER': 'Outdoors & Recreation',
    'SOIL': 'Outdoors & Recreation', 'FERTILIZER': 'Outdoors & Recreation', 'OUTDOOR_LIVING': 'Outdoors & Recreation',
    'SPORTING_GOODS': 'Outdoors & Recreation', 'SAFETY_GLASSES': 'Outdoors & Recreation',
    'LAWN_MOWER': 'Outdoors & Recreation',
    'VEHICLE_WIND_DEFLECTOR': 'Outdoors & Recreation', 'VEHICLE_TIRE': 'Outdoors & Recreation',
    'BICYCLE_CARGO_RACK': 'Outdoors & Recreation',
    'SPORT_HELMET': 'Outdoors & Recreation', 'CARGO_STRAP': 'Outdoors & Recreation', 'SLED': 'Outdoors & Recreation',
    'TRAMPOLINE': 'Outdoors & Recreation', 'FISHING_NET': 'Outdoors & Recreation', 'TENT': 'Outdoors & Recreation',
    'RECREATION_BALL': 'Outdoors & Recreation', 'SANDBOX': 'Outdoors & Recreation',
    'VEHICLE_BUMPER': 'Outdoors & Recreation',
    'SPLASH_POOL': 'Outdoors & Recreation', 'POOL_COVER': 'Outdoors & Recreation',
    'AIMING_SCOPE_SIGHT': 'Outdoors & Recreation',
    'SPORT_NET': 'Outdoors & Recreation', 'CARABINER': 'Outdoors & Recreation', 'CYCLING_TIRE': 'Outdoors & Recreation',
    'VEHICLE_SEAT_COVER': 'Outdoors & Recreation', 'BARBECUE_GRILL': 'Outdoors & Recreation',
    'FIRE_PIT': 'Outdoors & Recreation',
    'GARDEN_TOOL_SET': 'Outdoors & Recreation', 'AIR_PUMP': 'Outdoors & Recreation',
    'SWIMMING_POOL': 'Outdoors & Recreation',
    'PESTICIDE': 'Outdoors & Recreation', 'KAYAK': 'Outdoors & Recreation', 'GREENHOUSE': 'Outdoors & Recreation',
    'TRACTION_CLEAT': 'Outdoors & Recreation', 'BICYCLE': 'Outdoors & Recreation',
    'BICYCLE_BELL': 'Outdoors & Recreation',
    'BUBBLE_MAKER': 'Outdoors & Recreation', 'COMPOST_BIN': 'Outdoors & Recreation',
    'SOLID_FIRE_FUEL': 'Outdoors & Recreation',
    'LEAF_BLOWER': 'Outdoors & Recreation', 'SNOW_BLOWER': 'Outdoors & Recreation',
    'PICNIC_HOLDER': 'Outdoors & Recreation', 'WHEEL': 'Outdoors & Recreation', 'SPORT_GOAL': 'Outdoors & Recreation',
    'SPORT_MITT': 'Outdoors & Recreation', 'DIVE_MASK': 'Outdoors & Recreation',
    'SNORKELING_SET': 'Outdoors & Recreation',
    'GOLF_CART': 'Outdoors & Recreation', 'TARGET_TOSSING_GAME': 'Outdoors & Recreation',
    'RAKE': 'Outdoors & Recreation',
    'SPORT_RACKET': 'Outdoors & Recreation', 'ROLLER_SKATE': 'Outdoors & Recreation',
    'HYDRATION_PACK': 'Outdoors & Recreation', 'MESS_KIT': 'Outdoors & Recreation',
    'NETTING_COVER': 'Outdoors & Recreation',
    'DRIP_IRRIGATION_KIT': 'Outdoors & Recreation', 'SPORT_BAT': 'Outdoors & Recreation',
    'SLEEPING_MAT': 'Outdoors & Recreation',
    'SOLAR_PANEL': 'Outdoors & Recreation', 'GARDEN_EDGING': 'Outdoors & Recreation',
    'POOL_VACUUM': 'Outdoors & Recreation',
    'AWNING': 'Outdoors & Recreation', 'SNOWSHOE': 'Outdoors & Recreation', 'SPORT_BOARD_SKI': 'Outdoors & Recreation',
    'GOLF_CLUB': 'Outdoors & Recreation',
    'KITE': 'Outdoors & Recreation', 'CLIMBING_HOLD': 'Outdoors & Recreation', 'PADDLEBOARD': 'Outdoors & Recreation',
    'TOW_SPORTS_LINE': 'Outdoors & Recreation', 'OUTBOARD_MOTOR': 'Outdoors & Recreation',
    'IRRIGATION_EQUIPMENT': 'Outdoors & Recreation',
    'CAMPING_EQUIPMENT': 'Outdoors & Recreation', 'SPORT_TARGET': 'Outdoors & Recreation',
    'SPORTS': 'Outdoors & Recreation',
    'Lawn & Patio': 'Outdoors & Recreation',

    'TOY': 'Hobbies & Collectibles', 'GAMES': 'Hobbies & Collectibles', 'YARN': 'Hobbies & Collectibles',
    'NEEDLE': 'Hobbies & Collectibles', 'TUNIC': 'Hobbies & Collectibles',
    'BLANK_BOOK': 'Hobbies & Collectibles', 'PUZZLES': 'Hobbies & Collectibles', 'BOARD_GAME': 'Hobbies & Collectibles',
    'PHYSICAL_MOVIE': 'Hobbies & Collectibles', 'INSTRUMENT_PARTS_AND_ACCESSORIES': 'Hobbies & Collectibles',
    'PHYSICAL_TV_SERIES': 'Hobbies & Collectibles', 'ENTERTAINMENT_MEMORABILIA': 'Hobbies & Collectibles',
    'SCIENCE_FUNDAMENTALS_KIT': 'Hobbies & Collectibles', 'GUN_HOLSTER': 'Hobbies & Collectibles',
    'PHYSICAL_SOFTWARE': 'Hobbies & Collectibles',
    'MAGNIFIER': 'Hobbies & Collectibles', 'BALLOON': 'Hobbies & Collectibles',
    'PARTY_DECORATION_PACK': 'Hobbies & Collectibles',
    'COLLECTIBLE_CARD': 'Hobbies & Collectibles', 'CROCHET_HOOK': 'Hobbies & Collectibles',
    'SEWING_PATTERN': 'Hobbies & Collectibles',
    'COLLECTIBLE_COINS': 'Hobbies & Collectibles', 'MONEY_BANK': 'Hobbies & Collectibles',
    'PARTY_FAVOR': 'Hobbies & Collectibles',
    'TRADING_CARDS_CARDS_SETS': 'Hobbies & Collectibles', 'CAPO': 'Hobbies & Collectibles',
    'TELESCOPE': 'Hobbies & Collectibles',
    'SMOKING_PIPE': 'Hobbies & Collectibles', 'MUSICAL_INSTRUMENTS': 'Hobbies & Collectibles',
    'KEYBOARD_INSTRUMENTS': 'Hobbies & Collectibles',
    'REINFORCED_ART_SURFACE': 'Hobbies & Collectibles', 'ART': 'Hobbies & Collectibles',
    'SKATEBOARD': 'Hobbies & Collectibles', 'HOBBIES': 'Hobbies & Collectibles',
    'MARBLE_TRACK': 'Hobbies & Collectibles',
    'PHOTOGRAPHIC_STUDIO_ITEMS': 'Hobbies & Collectibles', 'MUSICAL_INSTRUMENT_AMPLIFIER': 'Hobbies & Collectibles',
    'GUITARS': 'Hobbies & Collectibles', 'SEWING_BUTTON': 'Hobbies & Collectibles', 'YO_YO': 'Hobbies & Collectibles',
    'PINATA': 'Hobbies & Collectibles',
    'GUILD_ACCESSORIES': 'Hobbies & Collectibles', 'SWORD': 'Hobbies & Collectibles',
    'DOWNLOADABLE_TV_SEASON': 'Hobbies & Collectibles',
    'CONFETTI': 'Hobbies & Collectibles', 'WHISTLE': 'Hobbies & Collectibles',
    'FLEXIBLE_MAGNET': 'Hobbies & Collectibles',
    'GAME_CALL': 'Hobbies & Collectibles', 'TRADING_CARDS_UNGRADED_INSERTS': 'Hobbies & Collectibles',
    'TRADING_CARDS_FACTORY_SEALED': 'Hobbies & Collectibles',
    'TRADING_CARDS_MISC_TRADING_CARDS': 'Hobbies & Collectibles', 'BULLION': 'Hobbies & Collectibles',
    'CIGARETTE_CASE': 'Hobbies & Collectibles',
    'CARD_SHUFFLER': 'Hobbies & Collectibles', 'COLLECTIBLES': 'Hobbies & Collectibles',
    'MODEL': 'Hobbies & Collectibles', 'PERCUSSION_INSTRUMENTS': 'Hobbies & Collectibles',
    'SKILL_APPLICATION': 'Hobbies & Collectibles', 'MISC_WORLD_INSTRUMENTS': 'Hobbies & Collectibles',
    'SPORT_POM_POM': 'Hobbies & Collectibles', 'Sports': 'Hobbies & Collectibles',
    'Toy': 'Hobbies & Collectibles', 'Hardcover': 'Hobbies & Collectibles',
    'HISTORICAL_COLLECTIBLES': 'Hobbies & Collectibles',

    'AUTO_PART': 'Automotive', 'WIPER_BLADE': 'Automotive', 'CARBURETOR': 'Automotive',
    'VEHICLE_MIRROR': 'Automotive', 'VEHICLE_SEAT': 'Automotive', 'VEHICLE_EMBLEM': 'Automotive',
    'ENGINE_COMPONENT_CAP': 'Automotive', 'IGNITION_COIL': 'Automotive', 'TOW_HITCH': 'Automotive',
    'VEHICLE_GRILLE': 'Automotive', 'VEHICLE_EXTERIOR_GUARD': 'Automotive', 'VEHICLE_COVER': 'Automotive',
    'HUBCAP_WHEEL_COVER': 'Automotive', 'VEHICLE_BODY_PANEL': 'Automotive', 'FUEL_PUMP': 'Automotive',
    'VEHICLE_SCAN_TOOL': 'Automotive', 'VEHICLE_MAT': 'Automotive', 'VEHICLE_INTERIOR_SHADE': 'Automotive',
    'VEHICLE_CARGO_CARRIER': 'Automotive', 'TRANSPORT_RACK': 'Automotive', 'SNOW_CHAIN': 'Automotive',
    'HANDLEBAR_GRIP': 'Automotive', 'HANDLEBAR': 'Automotive', 'RAMP': 'Automotive',
    'VEHICLE_MOLDING': 'Automotive', 'SPARK_PLUG': 'Automotive', 'ENGINE_EXHAUST_PIPE': 'Automotive',
    'MOTOR_ENGINE_FUEL_TANK': 'Automotive', 'CAR_ALARM': 'Automotive', 'VEHICLE_HORN': 'Automotive',
    'VEHICLE_WRAP': 'Automotive', 'VEHICLE_SPOILER': 'Automotive', 'VEHICLE_CONTROL_ARM': 'Automotive',
    'TIRE_COVER': 'Automotive', 'CARGO_NET': 'Automotive', 'KICK_SCOOTER': 'Automotive',
    'VEHICLE_RAIL': 'Automotive', 'TIRES': 'Automotive', 'VEHICLE_LIFT_KIT': 'Automotive',
    'AUTO_CHEMICAL': 'Automotive', 'WINDSHIELD_SNOW_COVER': 'Automotive', 'TRAILER_HITCH_COVER': 'Automotive',
    'FUEL_INJECTOR': 'Automotive', 'VEHICLE_HEAT_SHIELD': 'Automotive', 'VEHICLE_BALL_JOINT': 'Automotive',
}

reverse_word_map = {}
for keyword, category in keyword_map.items():
    words = keyword.split('_')
    for word in words:
        if word and word not in reverse_word_map:
            reverse_word_map[word] = category

def reverse_lookup(cat_name):
    words = str(cat_name).split("_")
    for word in words:
        if word in reverse_word_map:
            return reverse_word_map[word]
    return


# def create_general_category(df, category_col = "Category"):
#     """
#     Maps a detailed category name to a new general category based on keywords.
#     """
#
#     category_series = df[category_col].astype(str)
#     conditions = []
#     choices = []
#
#     for keyword, general_cat in keyword_map.items():
#         conditions.append(category_series.str.contains(keyword))
#         choices.append(general_cat)
#
#     df['General_Category'] = np.select(
#         condlist=conditions,
#         choicelist=choices,
#         default='Other'
#     )
#     return df


# 1. Load your dataset
df = pd.read_csv('amazon-purchases.csv')
df = df.dropna()

df['General_Category'] = df['Category'].apply(reverse_lookup)

print(df['General_Category'].unique().tolist())
